### ISSUE TITLE
Link Request

### ISSUE THREAD

**Issue by davechurchill** [SKTBrain/awesome-starcraftAI#4]
You may want to link to our SC data extract:

https://docs.google.com/spreadsheets/d/1jlYDkXW2pQey1oGJlQRBiGjdMs0kfrdHAwzVI2zAjrU/edit?usp=sharing

https://docs.google.com/spreadsheets/d/1YWFzY0_MEE4fOy9HrvZCYSpRqjgSBdCeRYVxB6zmJpQ/edit?usp=sharing

https://docs.google.com/spreadsheets/d/1FpB8e7VJYubaqTtMLoc457a319Wu8yT8jTM6hPq6pT8/edit?usp=sharing

**Comment by hshyunsookim** [comment]
Links added, thanks!
